In [21]:
import numpy as np
from sklearn.datasets import load_iris
iris=load_iris()

In [4]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

In [23]:
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_scores

C:\Users\Liki\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [24]:
np.average(l_scores)

0.9733333333333334

In [25]:
svm_scores=cross_val_score(SVC(),iris.data,iris.target)
svm_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [26]:
np.average(svm_scores)

0.9666666666666666

In [27]:
tree_scores=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
tree_scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [28]:
np.average(tree_scores)

0.9600000000000002